services:
  mysql:
    image: mysql:8.0
    container_name: mysql_vivienda_ideal
    restart: always
    environment:
      MYSQL_DATABASE: vivienda_ideal
      MYSQL_ROOT_PASSWORD: mundoLibre2025!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

volumes:
  mysql_data: